CREATE TABLE Projects (
    ProjectId VARCHAR(50) PRIMARY KEY,
    EnterpriseProjectTypeDescription VARCHAR(255),
    EnterpriseProjectTypeId VARCHAR(50),
    EnterpriseProjectTypeIsDefault BIT,
    EnterpriseProjectTypeName VARCHAR(255),
    OptimizerCommitDate DATETIME,
    OptimizerDecisionAliasLookupTableId VARCHAR(50),
    OptimizerDecisionAliasLookupTableValueId VARCHAR(50),
    OptimizerDecisionID VARCHAR(50),
    OptimizerDecisionName VARCHAR(255),
    OptimizerSolutionName VARCHAR(255),
    ParentProjectId VARCHAR(50),
    PlannerCommitDate DATETIME,
    PlannerDecisionAliasLookupTableId VARCHAR(50),
    PlannerDecisionAliasLookupTableValueId VARCHAR(50),
    PlannerDecisionID VARCHAR(50),
    PlannerDecisionName VARCHAR(255),
    PlannerEndDate DATETIME,
    PlannerSolutionName VARCHAR(255),
    PlannerStartDate DATETIME,
    ProjectActualCost DECIMAL(18, 6),
    ProjectActualDuration DECIMAL(18, 6),
    ProjectActualFinishDate DATETIME,
    ProjectActualOvertimeCost DECIMAL(18, 6),
    ProjectActualOvertimeWork DECIMAL(18, 6),
    ProjectActualRegularCost DECIMAL(18, 6),
    ProjectActualRegularWork DECIMAL(18, 6),
    ProjectActualStartDate DATETIME,
    ProjectActualWork DECIMAL(18, 6),
    ProjectACWP DECIMAL(18, 6),
    ProjectAuthorName VARCHAR(255),
    ProjectBCWP DECIMAL(18, 6),
    ProjectBCWS DECIMAL(18, 6),
    ProjectBudgetCost DECIMAL(18, 6),
    ProjectBudgetWork DECIMAL(18, 6),
    ProjectCalculationsAreStale BIT,
    ProjectCalendarDuration INT,
    ProjectCategoryName VARCHAR(255),
    ProjectCompanyName VARCHAR(255),
    ProjectCost DECIMAL(18, 6),
    ProjectCostVariance DECIMAL(18, 6),
    ProjectCPI DECIMAL(18, 6),
    ProjectCreatedDate DATETIME,
    ProjectCurrency VARCHAR(3),
    ProjectCV DECIMAL(18, 6),
    ProjectCVP DECIMAL(18, 13),
    ProjectDescription VARCHAR(MAX),
    ProjectDuration DECIMAL(18, 6),
    ProjectDurationVariance DECIMAL(18, 6),
    ProjectEAC DECIMAL(18, 6),
    ProjectEarlyFinish DATETIME,
    ProjectEarlyStart DATETIME,
    ProjectEarnedValueIsStale BIT,
    ProjectEnterpriseFeatures BIT,
    ProjectFinishDate DATETIME,
    ProjectFinishVariance DECIMAL(18, 6),
    ProjectFixedCost DECIMAL(18, 6),
    ProjectIdentifier VARCHAR(50),
    ProjectKeywords VARCHAR(MAX),
    ProjectLateFinish DATETIME,
    ProjectLateStart DATETIME,
    ProjectLastPublishedDate DATETIME,
    ProjectManagerName VARCHAR(255),
    ProjectModifiedDate DATETIME,
    ProjectName VARCHAR(255),
    ProjectOvertimeCost DECIMAL(18, 6),
    ProjectOvertimeWork DECIMAL(18, 6),
    ProjectOwnerId VARCHAR(50),
    ProjectOwnerName VARCHAR(255),
    ProjectPercentCompleted INT,
    ProjectPercentWorkCompleted INT,
    ProjectRegularCost DECIMAL(18, 6),
    ProjectRegularWork DECIMAL(18, 6),
    ProjectRemainingCost DECIMAL(18, 6),
    ProjectRemainingDuration DECIMAL(18, 6),
    ProjectRemainingOvertimeCost DECIMAL(18, 6),
    ProjectRemainingOvertimeWork DECIMAL(18, 6),
    ProjectRemainingRegularCost DECIMAL(18, 6),
    ProjectRemainingRegularWork DECIMAL(18, 6),
    ProjectRemainingWork DECIMAL(18, 6),
    ProjectResourcePlanWork DECIMAL(18, 6),
    ProjectSPI DECIMAL(18, 6),
    ProjectStartDate DATETIME,
    ProjectStartVariance DECIMAL(18, 6),
    ProjectStatusDate DATETIME,
    ProjectSubject VARCHAR(MAX),
    ProjectSV DECIMAL(18, 6),
    ProjectSVP DECIMAL(18, 13),
    ProjectTCPI DECIMAL(18, 6),
    ProjectTimephased VARCHAR(50),
    ProjectTitle VARCHAR(255),
    ProjectType INT,
    ProjectVAC DECIMAL(18, 6),
    ProjectWork DECIMAL(18, 6),
    ProjectWorkspaceInternalUrl VARCHAR(MAX),
    ProjectWorkVariance DECIMAL(18, 6),
    ResourcePlanUtilizationDate DATETIME,
    ResourcePlanUtilizationType INT,
    WorkflowCreatedDate DATETIME,
    WorkflowError VARCHAR(MAX),
    WorkflowErrorResponseCode VARCHAR(50),
    WorkflowInstanceId VARCHAR(50),
    WorkflowOwnerId VARCHAR(50),
    WorkflowOwnerName VARCHAR(255),
    ProjectDepartments VARCHAR(MAX),
    SnapshotDate DATETIME
);
